app/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# TODO remove for productive...
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include(('base.urls', 'base',), namespace='base')),
    path('admin/', admin.site.urls, name='admin'),
    path('log/', include(('log_manager.urls', 'transcripts',), namespace='log_manager')),
    path('support/', include(('support_manager.urls', 'support_manager',), namespace='support_manager')),
] + staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_title = 'Django Discord Bot Template'

app/log_manager/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('transcripts', views.TranscriptsView.as_view(), name='show_all'),
    path('transcript/<uuid:transcript_id>', views.TranscriptView.as_view(), name='show'),
]

app/log_manager/models.py
from django.db import models
from django.utils import timezone

from uuid import uuid4

from base.models import User


class Transcript(models.Model):
    public_id = models.UUIDField(default=uuid4)
    channel_name = models.CharField(max_length=120, blank=False, null=False)
    created = models.DateTimeField(blank=True, null=True, default=timezone.now)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="created_by_user")
    notes = models.TextField(max_length=8192, blank=True, null=True)

    def __str__(self):
        return f'{self.public_id} ({self.channel_name}, {self.created.strftime("%Y-%m-%d %H:%M:%S")})'

app/log_manager/views.py
from pathlib import Path

from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponseNotFound, HttpResponse, HttpRequest
from uuid import uuid4

from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View

from log_manager.models import Transcript


class TranscriptsView(View):

    @method_decorator(login_required)
    @method_decorator(permission_required('log_manager.view_transcript'))
    def get(self, request: HttpRequest):
        return render(request, "transcripts.html", context={
            "transcripts": [
                {
                    "id": t.public_id,
                    "channel_name": t.channel_name,
                    "created": t.created,
                } for t in Transcript.objects.all()
            ]
        })


class TranscriptView(View):
    @method_decorator(login_required)
    @method_decorator(permission_required('log_manager.view_transcript'))
    def get(self, request: HttpRequest, transcript_id: uuid4):
        transcript = Transcript.objects.filter(public_id=transcript_id).first()
        f = Path(f'{settings.BASE_DIR}/media/transcripts/{transcript_id}.html')

        if not transcript or not f.is_file():
            return HttpResponseNotFound()

        with f.open('r') as f:
            return HttpResponse(f.read())

    @method_decorator(login_required)
    @method_decorator(permission_required('log_manager.delete_transcript'))
    def delete(self, request: HttpRequest, transcript_id: uuid4):
        transcript = Transcript.objects.filter(public_id=transcript_id).first()

        f = Path(f'{settings.BASE_DIR}/media/transcripts/{transcript_id}.html')
        if f.is_file():
            f.unlink(missing_ok=True)

        if not transcript:
            return HttpResponseNotFound()

        transcript.delete()
        return HttpResponse(status=204)

app/log_manager/templates/transcript.html
{% load custom_filter %}
<!DOCTYPE html>
<html>
<head>
    <title>{{ guild.name }} - #{{ channel_name }}</title>
    <meta charset=utf-8>
    <meta name=viewport content="width=device-width">
    <style>
        @font-face {
        font-family: Whitney;
        src: url(https://discordapp.com/assets/6c6374bad0b0b6d204d8d6dc4a18d820.woff);
        font-weight: 300
    }

    @font-face {
        font-family: Whitney;
        src: url(https://discordapp.com/assets/e8acd7d9bf6207f99350ca9f9e23b168.woff);
        font-weight: 400
    }

    @font-face {
        font-family: Whitney;
        src: url(https://discordapp.com/assets/3bdef1251a424500c1b3a78dea9b7e57.woff);
        font-weight: 500
    }

    @font-face {
        font-family: Whitney;
        src: url(https://discordapp.com/assets/be0060dafb7a0e31d2a1ca17c0708636.woff);
        font-weight: 600
    }

    @font-face {
        font-family: Whitney;
        src: url(https://discordapp.com/assets/8e12fb4f14d9c4592eb8ec9f22337b04.woff);
        font-weight: 700
    }

    body {
        font-family: Whitney, "Helvetica Neue", Helvetica, Arial, sans-serif;
        font-size: 17px
    }

    a {
        text-decoration: none
    }

    a:hover {
        text-decoration: underline
    }

    img {
        object-fit: contain
    }

    .markdown {
        white-space: pre-wrap;
        line-height: 1.3;
        overflow-wrap: break-word
    }

    .spoiler {
        border-radius: 3px
    }

    .quote {
        border-left: 4px solid;
        border-radius: 3px;
        margin: 8px 0;
        padding-left: 10px
    }

    .pre {
        font-family: Consolas, "Courier New", Courier, monospace
    }

    .pre--multiline {
        margin-top: 4px;
        padding: 8px;
        border: 2px solid;
        border-radius: 5px
    }

    .pre--inline {
        padding: 2px;
        border-radius: 3px;
        font-size: 85%
    }

    .mention {
        font-weight: 500
    }

    .emoji {
        width: 1.45em;
        height: 1.45em;
        margin: 0 1px;
        vertical-align: -.4em
    }

    .emoji--small {
        width: 1rem;
        height: 1rem
    }

    .emoji--large {
        width: 2rem;
        height: 2rem
    }

    .info {
        display: flex;
        max-width: 100%;
        margin: 0 5px 10px
    }

    .info__guild-icon-container {
        flex: 0
    }

    .info__guild-icon {
        max-width: 88px;
        max-height: 88px
    }

    .info__metadata {
        flex: 1;
        margin-left: 10px
    }

    .info__guild-name {
        font-size: 1.4em
    }

    .info__channel-name {
        font-size: 1.2em
    }

    .info__channel-topic {
        margin-top: 2px
    }

    .info__channel-message-count {
        margin-top: 2px
    }

    .info__channel-date-range {
        margin-top: 2px
    }

    .chatlog {
        max-width: 100%;
        margin-bottom: 24px
    }

    .chatlog__message-group {
        display: flex;
        margin: 0 10px;
        padding: 15px 0 0;
        border-top: 1px solid
    }

    .chatlog__author-avatar-container {
        flex: 0;
        width: 40px;
        height: 40px
    }

    .chatlog__author-avatar {
        border-radius: 50%;
        height: 40px;
        width: 40px
    }

    .chatlog__messages {
        flex: 1;
        min-width: 50%;
        margin-left: 20px
    }

    .chatlog__author-name {
        font-size: 1em;
        font-weight: 500
    }

    .chatlog__timestamp {
        margin-left: 5px;
        font-size: .75em
    }

    .chatlog__message {
        padding: 2px 5px;
        margin-right: -5px;
        margin-left: -5px;
        background-color: transparent;
        transition: background-color 1s ease
    }

    .chatlog__content {
        font-size: .9375em;
        word-wrap: break-word
    }

    .chatlog__edited-timestamp {
        margin-left: 3px;
        font-size: .8em
    }

    .chatlog__attachment-thumbnail {
        margin-top: 5px;
        max-width: 50%;
        max-height: 500px;
        border-radius: 3px
    }

    .chatlog__embed {
        margin-top: 5px;
        display: flex;
        max-width: 520px
    }

    .chatlog__embed-color-pill {
        flex-shrink: 0;
        width: 4px;
        border-top-left-radius: 3px;
        border-bottom-left-radius: 3px
    }

    .chatlog__embed-content-container {
        display: flex;
        flex-direction: column;
        padding: 8px 10px;
        border: 1px solid;
        border-top-right-radius: 3px;
        border-bottom-right-radius: 3px
    }

    .chatlog__embed-content {
        width: 100%;
        display: flex
    }

    .chatlog__embed-text {
        flex: 1
    }

    .chatlog__embed-author {
        display: flex;
        align-items: center;
        margin-bottom: 5px
    }

    .chatlog__embed-author-icon {
        width: 20px;
        height: 20px;
        margin-right: 9px;
        border-radius: 50%
    }

    .chatlog__embed-author-name {
        font-size: .875em;
        font-weight: 600
    }

    .chatlog__embed-title {
        margin-bottom: 4px;
        font-size: .875em;
        font-weight: 600
    }

    .chatlog__embed-description {
        font-weight: 500;
        font-size: 14px
    }

    .chatlog__embed-fields {
        display: flex;
        flex-wrap: wrap
    }

    .chatlog__embed-field {
        flex: 0;
        min-width: 100%;
        max-width: 506px;
        padding-top: 10px
    }

    .chatlog__embed-field--inline {
        flex: 1;
        flex-basis: auto;
        min-width: 150px
    }

    .chatlog__embed-field-name {
        margin-bottom: 4px;
        font-size: .875em;
        font-weight: 600
    }

    .chatlog__embed-field-value {
        font-size: .875em;
        font-weight: 500
    }

    .chatlog__embed-thumbnail {
        flex: 0;
        margin-left: 20px;
        max-width: 80px;
        max-height: 80px;
        border-radius: 3px
    }

    .chatlog__embed-image-container {
        margin-top: 10px
    }

    .chatlog__embed-image {
        max-width: 500px;
        max-height: 400px;
        border-radius: 3px
    }

    .chatlog__embed-footer {
        margin-top: 10px
    }

    .chatlog__embed-footer-icon {
        margin-right: 4px;
        width: 20px;
        height: 20px;
        border-radius: 50%;
        vertical-align: middle
    }

    .chatlog__embed-footer-text {
        font-weight: 500;
        font-size: .75em
    }

    .chatlog__reactions {
        display: flex
    }

    .chatlog__reaction {
        display: flex;
        align-items: center;
        margin: 6px 2px 2px;
        padding: 3px 6px;
        border-radius: 3px
    }

    .chatlog__reaction-count {
        min-width: 9px;
        margin-left: 6px;
        font-size: .875em
    }

    .chatlog__bot-tag {
        margin-left: .3em;
        background: #7289da;
        color: #fff;
        font-size: .625em;
        padding: 1px 2px;
        border-radius: 3px;
        vertical-align: middle;
        line-height: 1.3;
        position: relative;
        top: -.2em
    }</style>
    <style>
        body {
        background-color: #36393e;
        color: #dcddde
    }

    a {
        color: #0096cf
    }

    .spoiler {
        background-color: rgba(255, 255, 255, .1)
    }

    .quote {
        border-color: #4f545c
    }

    .pre {
        background-color: #2f3136 !important
    }

    .pre--multiline {
        border-color: #282b30 !important;
        color: #839496 !important
    }

    .mention {
        color: #7289da
    }

    .info__guild-name {
        color: #fff
    }

    .info__channel-name {
        color: #fff
    }

    .info__channel-topic {
        color: #fff
    }

    .chatlog__message-group {
        border-color: rgba(255, 255, 255, .1)
    }

    .chatlog__author-name {
        color: #fff
    }

    .chatlog__timestamp {
        color: rgba(255, 255, 255, .2)
    }

    .chatlog__message--highlighted {
        background-color: rgba(114, 137, 218, .2) !important
    }

    .chatlog__message--pinned {
        background-color: rgba(249, 168, 37, .05)
    }

    .chatlog__edited-timestamp {
        color: rgba(255, 255, 255, .2)
    }

    .chatlog__embed-content-container {
        background-color: rgba(46, 48, 54, .3);
        border-color: rgba(46, 48, 54, .6)
    }

    .chatlog__embed-author-name {
        color: #fff
    }

    .chatlog__embed-author-name-link {
        color: #fff
    }

    .chatlog__embed-title {
        color: #fff
    }

    .chatlog__embed-description {
        color: rgba(255, 255, 255, .6)
    }

    .chatlog__embed-field-name {
        color: #fff
    }

    .chatlog__embed-field-value {
        color: rgba(255, 255, 255, .6)
    }

    .chatlog__embed-footer {
        color: rgba(255, 255, 255, .6)
    }

    .chatlog__reaction {
        background-color: rgba(255, 255, 255, .05)
    }

    .chatlog__reaction-count {
        color: rgba(255, 255, 255, .3)
    }</style>
</head>
<body>
<div class=info>
    <div class=info__guild-icon-container>
        <img class=info__guild-icon src="{{ guild.icon }}">
    </div>
    <div class=info__metadata>
        <div class=info__guild-name>{{ guild.name }}</div>
        <div class=info__channel-name>#{{ channel_name }}</div>
        <div class=info__channel-message-count>{{ messages|length }} Message{% if messages|length > 1 %}s{% endif %}</div>
    </div>
</div>
<div class=chatlog>
    {% for msg in messages %}
        <div class=chatlog__message-group>
            <div class=chatlog__author-avatar-container>
                <img class=chatlog__author-avatar src="{{ msg.author.avatar }}">
            </div>
            <div class=chatlog__messages>
                <span class=chatlog__author-name title="{{ msg.authorname }}"
                      data-user-id="{{ msg.author.id }}">{{ msg.author.name }}</span>
                {% if msg.bot == True %}
                    <span class=chatlog__bot-tag>BOT</span>
                {% endif %}
                {% for a in msg.attachments %}
                    <div class=chatlog__attachment>
                        {#{% set splitted = a.url.split('/') %}#}
                        {#<a href="{{ a.url }}">Attachment: {{ splitted[splitted|length - 1] }} {{ a.size }}</a>#}
                    </div>
                {% endfor %}
                {% if msg.content %}
                    <span class=chatlog__timestamp>{{ msg.timestamp }}</span>
                    <div class=chatlog__message id=message-{{ msg.id }} data-message-id={{ msg.id }}>
                    <div class=chatlog__content>
                        <p><span>{{ msg.content|regexr|markdown }}</span></p>
                        <span></span>
                    </div>
                {% endif %}
                {% for e in msg.embeds %}
                    <div class=chatlog__embed>
                        <div class=chatlog__embed-color-pill style=background-color:{{ e.color }}></div>
                        <div class=chatlog__embed-content-container>
                            <div class=chatlog__embed-content>
                                <div class=chatlog__embed-text>
                                    <div class=chatlog__embed-title><span class=markdown>{{ e.title|markdown }}</span></div>
                                    <div class=chatlog__embed-description><p><span
                                            class=markdown>{{ e.description|regexr|markdown }}</span></p></div>
                                    {% if e.fields %}
                                        <div class=chatlog__embed-fields>
                                            {% for f in e.fields %}
                                                <div class=chatlog__embed-field-name><span
                                                        class=markdown>{{ f.title|markdown }} </span></div><br>
                                                <div class=chatlog__embed-field-value><p><span
                                                        class=markdown>{{ f.description|regexr|markdown }}</span></p></div>
                                            {% endfor %}
                                        </div>
                                    {% endif %}
                                </div>
                                {% if e.thumbnail %}
                                    <div class=chatlog__embed-thumbnail-container>
                                        <a class=chatlog__embed-thumbnail-link>
                                            <img class=chatlog__embed-thumbnail src="{{ e.thumbnail }}">
                                        </a>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <div class=chatlog__reactions>
                    <div class=chatlog__reactions>
                        {% for reaction in msg.reactions %}
                            <div class=chatlog__reaction>
                                <img class=emoji--small alt="{{ reaction.emoji }}" title="{{ reaction.emoji }}"
                                    src="{{ reaction.src }}"><span
                                    class=chatlog__reaction-count>{{ reaction.count }}</span>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
</body>
</html>

app/log_manager/templates/transcripts.html
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Transcripts</title>
        <link rel="stylesheet"
              href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
              crossorigin="anonymous">
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
              integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
              crossorigin="anonymous" />
    </head>
    <body class="bg-dark">
        {% include 'navigation.html' %}
        <div class="container my-3">
            {% if transcripts %}
            <div class="card">
                <h5 class="card-header" style="text-align: center;">Transcripts</h5>
                <div class="card-body">
                    <ul>
                        {% for t in transcripts %}
                        <li><a href="{% url 'log_manager:show' t.id %}">#{{ t.channel_name }} ({{ t.created|naturalday }})</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            {% else %}
            <p>Currently no transcripts exist, you can create a new transcript using the discord bot command <code>.save</code>.</p>
            {% endif %}
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
                integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
                integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
                crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
                integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
                crossorigin="anonymous"></script>
    </body>
</html>