app/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# TODO remove for productive...
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include(('base.urls', 'base',), namespace='base')),
    path('admin/', admin.site.urls, name='admin'),
    path('log/', include(('log_manager.urls', 'transcripts',), namespace='log_manager')),
    path('support/', include(('support_manager.urls', 'support_manager',), namespace='support_manager')),
] + staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_title = 'Django Discord Bot Template'

app/support_manager/urls.py
from django.urls import path

from .views import overview, edit, new, send_message


urlpatterns = [
    path('', overview, name='overview'),
    path('new/', new, name='new'),
    path('edit/<int:ticket_id>', edit, name='edit'),
    path('send/<int:ticket_id>', send_message, name='send_message')
]

app/support_manager/models.py
from django.db import models
from django.utils import timezone

from base.models import User


class Service(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Ticket(models.Model):
    STATES = [
        (0, 'Open'),
        (1, 'Pending'),
        (2, 'Closed'),
    ]
    PRIORITIES = [
        (0, 'Low'),
        (1, 'Normal'),
        (2, 'High'),
    ]

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=128)
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name="ticket_service")
    description = models.TextField()
    comment = models.TextField(blank=True, null=True)
    status = models.IntegerField('status', default=0, choices=STATES)
    priority = models.IntegerField('priority', default=0, choices=PRIORITIES)
    discord_notifications = models.BooleanField('discord_notifications', default=False)

    def __str__(self):
        info = "["

        # add status
        for _id, status in self.STATES:
            if _id != self.status:
                continue
            info += status
            break
        info += ", "

        # add priority
        for _id, priority in self.PRIORITIES:
            if _id != self.priority:
                continue
            info += priority
            break

        info += "]"
        return f'{info} {self.subject}'


class Message(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.SET_NULL, null=True, related_name="ticket_messages")
    from_team = models.BooleanField(default=True)
    created = models.DateTimeField(default=timezone.now)
    content = models.TextField()

app/support_manager/forms.py
from django import forms
from django.utils.translation import gettext as _
from .models import Service, Ticket


class TicketForm(forms.Form):
    subject = forms.CharField(max_length=128, widget=forms.TextInput(attrs={
        'placeholder': _('Subject'),
        'class': 'form-control',
    }), required=True)

    service = forms.ModelChoiceField(
        widget=forms.Select(attrs={
            'placeholder': _('Service'),
            'class': 'form-control',
        }),
        queryset=Service.objects.all(),
        required=True
    )

    description = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': _('Description'),
        'class': 'form-control',
    }), required=True)

    priority = forms.ChoiceField(
        widget=forms.Select(attrs={
            'placeholder': _('Priority'),
            'class': 'form-control',
        }),
        choices=Ticket.PRIORITIES,
        required=True
    )

    discord_notifications = forms.BooleanField(widget=forms.CheckboxInput(), required=False)

app/support_manager/views.py
import json

from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponseNotFound, HttpResponseForbidden, HttpResponse, HttpResponseBadRequest
from django.shortcuts import render, redirect
from django.utils.translation import gettext as _

from base.models import User
from base.service.event import trigger

from .models import Ticket, Service, Message
from .forms import TicketForm


@login_required
def overview(request: WSGIRequest):
    data = {
        "tickets": [
            {
                "id": t.id,
                "subject": t.subject,
                "service": t.service.name,
                "status": t.STATES[t.status][1],
            } for t in Ticket.objects.filter(owner=request.user).all()
        ],
    }
    return render(request, 'overview.html', context=data)


@login_required
def new(request: WSGIRequest):
    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():

            discord_notifications = 'discord_notifications' in request.POST \
                and request.POST['discord_notifications'] == 'on'

            ticket = Ticket(
                owner=request.user,
                subject=request.POST['subject'],
                service=Service.objects.filter(id=request.POST['service']).first(),
                description=request.POST['description'],
                priority=request.POST['priority'],
                discord_notifications=discord_notifications,
            )
            ticket.save()

            trigger(
                cog_name='support_manager',
                func_name='send_message',
                content=_(f"Ticket (#{ticket.id}) has been created!")
            )

            if discord_notifications and (user := User.objects.filter(user=request.user).first()):
                trigger(
                    cog_name='support_manager',
                    func_name='send_dm',
                    member_id=user.discord_id,
                    content=_(f"You're ticket (#{ticket.id}) has been created, you will receive updates!")
                )

            return redirect('support_manager:overview')
        else:
            messages.error(request, _('Something went wrong...'))

    data = {
        "form": TicketForm()
    }
    return render(request, 'new.html', context=data)


@login_required
def edit(request: WSGIRequest, ticket_id: int):
    if not ticket_id or not (ticket := Ticket.objects.filter(id=ticket_id).first()):
        return HttpResponseNotFound()

    if not ticket.owner == request.user:
        return HttpResponseForbidden()

    data = {
        "services": [
            {
                "id": s.id,
                "name": s.name,
            } for s in Service.objects.all()
        ],
        "form": {
            "id": ticket_id,
            "subject": ticket.subject,
            "service": ticket.service,
            "priority": ticket.priority,
            "status": ticket.status,
            "description": ticket.description,
            "messages": [
                {
                    "id": m.id,
                    "team": m.from_team,
                    "content": m.content,
                    "created": m.created,
                } for m in Message.objects.filter(ticket=ticket).all()
            ]
        },
    }
    return render(request, 'edit.html', context=data)


@login_required
def send_message(request: WSGIRequest, ticket_id: int):
    data = json.loads(request.body)
    if 'content' not in data:
        return HttpResponseBadRequest()

    ticket = Ticket.objects.filter(id=ticket_id).first()

    if not ticket:
        return HttpResponseNotFound()

    # send forbidden if ticket is already closed
    if not ticket.owner == request.user or ticket.status == Ticket.STATES[2]:
        return HttpResponseForbidden()

    message = Message(
        ticket=ticket,
        content=data['content'],
        from_team=False,
    )
    message.save()

    return HttpResponse()

app/support_manager/templates/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Tickets</title>
        <link rel="stylesheet"
              href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
              crossorigin="anonymous">
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
              integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
              crossorigin="anonymous" />
        <link rel="stylesheet" href="{% static 'assets/css/chat.css' %}">
    </head>
    <body class="bg-dark">
        {% include 'navigation.html' %}
        <div class="container">
            <div class="card my-3">
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <h5 style="margin-bottom: 0;">Ticket #{{ form.id }}</h5>
                        <a href="{% url 'support_manager:overview' %}"><i class="fas fa-undo float-right"></i></a>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label for="inputSubject" class="col-sm-2 col-form-label">Subject</label>
                            <div class="col-sm-10">
                                <input type="text" disabled class="form-control" id="inputSubject" value="{{ form.subject }}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputService" class="col-sm-2 col-form-label">Service</label>
                            <div class="col-sm-10">
                                <select type="text" disabled class="form-control" id="inputService">
                                    {% for service in services %}
                                        <option value="{{ service.id }}">{{ service.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputDescription" class="col-sm-2 col-form-label">Description</label>
                            <div class="col-sm-10">
                                <textarea type="text" disabled class="form-control" rows="15" id="inputDescription"
                                          placeholder="Describe your problem.">{{ form.description }}</textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputPriority" class="col-sm-2 col-form-label">Priority</label>
                            <div class="col-sm-10">
                                <select type="text" disabled class="form-control" id="inputPriority">
                                    <option value="0">Low</option>
                                    <option value="1">Normal</option>
                                    <option value="2">High</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputStatus" class="col-sm-2 col-form-label">Status</label>
                            <div class="col-sm-10">
                                <select type="text" disabled class="form-control" id="inputStatus">
                                    <option value="0">Open</option>
                                    <option value="1">Pending</option>
                                    <option value="2">Closed</option>
                                </select>
                            </div>
                        </div>
                        <div class="row justify-content-center">
                            <div class="col-sm-2"></div>
                            <div class="col-sm-10 chat">
                                <div class="card">
                                    <div class="card-body msg_card_body">
                                        {% for message in form.messages %}
                                        <div class="d-flex justify-content-{% if message.team %}start{% else %}end{% endif %} mb-4">
                                            <div class="msg_cotainer" style="min-width: 20%;">
                                                {{ message.content }}
                                                <div class="msg_time" id="{{ message.id }}" style="width: 100%; text-align: {% if message.team %}left{% else %}right{% endif %};"></div>
                                                <script>
                                                  document.getElementById("{{ message.id }}").value = new Intl.DateTimeFormat(navigator.language || navigator.userLanguage,{ dateStyle: 'short', timeStyle:'short' }).format(new Date('{{ message.created }}'));
                                                </script>
                                            </div>
                                        </div>
                                        {% endfor %}
                                    </div>
                                    <div class="card-footer">
                                        <div class="input-group">
                                            <textarea type="text" id="inputMessage" class="form-control type_msg" placeholder="Type your message..."></textarea>
                                            <div class="input-group-append">
                                                <button class="input-group-text send_btn" id="sendMessage">
                                                    <i class="fas fa-location-arrow"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
                integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
                integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
                crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
                integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
                crossorigin="anonymous"></script>
        <script>
            $('select[id="inputPriority"]').find('option[value="{{ form.priority }}"]').attr("selected",true);
            $('select[id="inputService"]').find('option[value="{{ form.service }}"]').attr("selected",true);
            $('select[id="inputStatus"]').find('option[value="{{ form.status }}"]').attr("selected",true);

            function getCookie(c_name) {
                if (document.cookie.length > 0) {
                    c_start = document.cookie.indexOf(c_name + "=");
                    if (c_start != -1) {
                        c_start = c_start + c_name.length + 1;
                        c_end = document.cookie.indexOf(";", c_start);
                        if (c_end == -1) c_end = document.cookie.length;
                        return unescape(document.cookie.substring(c_start,c_end));
                    }
                }
                return "";
            }

            document.getElementById('sendMessage').addEventListener('click', function (e) {
                // prevent page reload
                e.preventDefault();

                // get content
                let content = document.getElementById('inputMessage').value;
                if (content === undefined || content === "") {
                    return
                }

                // clear message textbox
                document.getElementById('inputMessage').value = "";

                // send message
                fetch('{% url 'support_manager:send_message' form.id %}', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json;charset=utf-8',
                        "X-CSRFToken": getCookie('csrftoken'),
                    },
                    credentials: 'include',
                    body: JSON.stringify({
                        "content": content,
                    })
                }).then(data => {
                    if (data.status === 200) {
                        location.reload();
                    }
                });
            });
        </script>
    </body>
</html>

app/support_manager/templates/new.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Tickets</title>
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
              integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
              crossorigin="anonymous" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css"
              integrity="sha512-P5MgMn1jBN01asBgU0z60Qk4QxiXo86+wlFahKrsQf37c9cro517WzVSPPV1tDKzhku2iJ2FVgL67wG03SGnNA=="
              crossorigin="anonymous" />
        <style>
            label {
                margin-bottom: 0;
            }
        </style>
    </head>
    <body class="bg-dark">
        {% include 'navigation.html' %}
        <div class="container">
            <div class="card my-3">
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <h5 style="margin-bottom: 0;">New Ticket</h5>
                        <a href="{% url 'support_manager:overview' %}"><i class="fas fa-undo float-right"></i></a>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label for="inputSubject" class="col-sm-2 col-form-label">Subject</label>
                            <div class="col-sm-10">
                                {{ form.subject }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputService" class="col-sm-2 col-form-label">Service</label>
                            <div class="col-sm-10">
                                {{ form.service }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputDescription" class="col-sm-2 col-form-label">Description</label>
                            <div class="col-sm-10">
                                {{ form.description }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-2"></div>
                            <div class="col-sm-10">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="d-flex justify-content-between align-items-center" style="column-gap: 10px;">
                                        Priority {{ form.priority }}
                                    </div>
                                    <div class="d-flex justify-content-between align-items-center" style="column-gap: 10px;">
                                        {{ form.discord_notifications }}
                                        <label for="inputDiscordNotification">Discord Notifications</label>
                                    </div>
                                    <button type="submit" class="btn btn-primary mb-2 float-right">Send</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
                integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
                integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"
                integrity="sha512-XKa9Hemdy1Ui3KSGgJdgMyYlUg1gM+QhL6cnlyTe2qzMCYm4nAZ1PsVerQzTTXzonUR+dmswHqgJPuwCq1MaAg=="
                crossorigin="anonymous"></script>
    </body>
</html>

app/support_manager/templates/overview.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Tickets</title>
        <link rel="stylesheet"
              href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
              crossorigin="anonymous">
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
              integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
              crossorigin="anonymous" />
    </head>
    <body class="bg-dark">
        {% include 'navigation.html' %}
        <div class="container">
            <div class="card my-3">
                <h5 class="card-header" style="text-align: center;">Tickets</h5>
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Subject</th>
                                <th scope="col">Service</th>
                                <th scope="col">Status</th>
                                <th scope="col"><a href="{% url 'support_manager:new' %}"><i class="fas fa-plus"></i></a></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for ticket in tickets %}
                                <tr>
                                    <th>{{ ticket.id }}</th>
                                    <td>{{ ticket.subject }}</td>
                                    <td>{{ ticket.service }}</td>
                                    <td>{{ ticket.status }}</td>
                                    <td><a href="{% url 'support_manager:edit' ticket.id %}"><i class="fas fa-pen"></i></a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
                integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
                integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
                crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
                integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
                crossorigin="anonymous"></script>
    </body>
</html>