app/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# TODO remove for productive...
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include(('base.urls', 'base',), namespace='base')),
    path('admin/', admin.site.urls, name='admin'),
    path('log/', include(('log_manager.urls', 'transcripts',), namespace='log_manager')),
    path('support/', include(('support_manager.urls', 'support_manager',), namespace='support_manager')),
] + staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_title = 'Django Discord Bot Template'

app/base/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('oauth/', views.discord_auth, name='discord_oauth'),
    path('oauth/redirect', views.discord_auth_redirect, name='discord_oauth_redirect')
]

app/log_manager/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('transcripts', views.TranscriptsView.as_view(), name='show_all'),
    path('transcript/<uuid:transcript_id>', views.TranscriptView.as_view(), name='show'),
]

app/support_manager/urls.py
from django.urls import path

from .views import overview, edit, new, send_message


urlpatterns = [
    path('', overview, name='overview'),
    path('new/', new, name='new'),
    path('edit/<int:ticket_id>', edit, name='edit'),
    path('send/<int:ticket_id>', send_message, name='send_message')
]

app/log_manager/models.py
from django.db import models
from django.utils import timezone

from uuid import uuid4

from base.models import User


class Transcript(models.Model):
    public_id = models.UUIDField(default=uuid4)
    channel_name = models.CharField(max_length=120, blank=False, null=False)
    created = models.DateTimeField(blank=True, null=True, default=timezone.now)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="created_by_user")
    notes = models.TextField(max_length=8192, blank=True, null=True)

    def __str__(self):
        return f'{self.public_id} ({self.channel_name}, {self.created.strftime("%Y-%m-%d %H:%M:%S")})'

app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Login</title>
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
              integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
              crossorigin="anonymous" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css"
              integrity="sha512-P5MgMn1jBN01asBgU0z60Qk4QxiXo86+wlFahKrsQf37c9cro517WzVSPPV1tDKzhku2iJ2FVgL67wG03SGnNA=="
              crossorigin="anonymous" />
    </head>
    <body class="bg-dark">
        <div class="container mt-5 text-white">
            <h1 align="center">Django Discord Bot Template</h1>
            <h2><a href="/admin">Admin Panel</a></h2>
            {% if not user.is_authenticated %}
                <h2><a href="/login">Login</a></h2>
            {% else %}
                <h2><a href="/logout">Logout</a></h2>
            {% endif %}
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
                integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
                integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"
                integrity="sha512-XKa9Hemdy1Ui3KSGgJdgMyYlUg1gM+QhL6cnlyTe2qzMCYm4nAZ1PsVerQzTTXzonUR+dmswHqgJPuwCq1MaAg=="
                crossorigin="anonymous"></script>
    </body>
</html>

app/templates/navigation.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="{% url 'base:index' %}">Django Discord Bot Template</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active"><a class="nav-link"
                                           href="{% url 'support_manager:overview' %}">Support</span></a></li>
            {% if perms.log_manager.view_transcript %}
            <li class="nav-item active"><a class="nav-link"
                                           href="{% url 'log_manager:show_all' %}">Transcripts</span></a></li>
            {% endif %}
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            {% if user.is_staff and user.is_superuser %}
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" id="userDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user-circle fa-fw"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="{% url 'admin:index' %}">Admin Dashboard</a>
                </div>
            </li>
            {% endif %}
            {% else %}
            <li class="nav-item active"><a class="nav-link" href="{% url 'base:discord_oauth' %}">Login</span></a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>